name: 测试
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
    inputs:
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 2

      - name: Setup python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Clone repositories
        run: |
          git clone https://x-access-token:${{ secrets.APK_SRC_REPO }}@github.com/beichen23333/BA-Text.git

      - name: Unpack TableCatalog.bytes and MediaCatalog.bytes
        run: |
          chmod +x ./MemoryPackRepacker
          ./MemoryPackRepacker deserialize media MediaCatalog.bytes BA-Text/MediaCatalog.json
          ./MemoryPackRepacker deserialize table TableCatalog.bytes BA-Text/TableCatalog.json

      - name: TableCatalog.bytes and MediaCatalog.bytes
        run: |
          python patch_table_catalog.py

      - name: 测试
        run: |
          chmod +x ./MemoryPackRepacker
          ./MemoryPackRepacker serialize table TableCatalog.json BA-Text/TableCatalog.bytes

      - name: Committing zip
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          cd BA-Text
          git add .
          if git diff-index --quiet HEAD; then
            echo "Skip committing."
          else
            git commit -m "Add version ${BA_VERSION_NAME}"
            git push origin
          fi
